/* SPDX-FileCopyrightText: 2014-present Kriasoft */
/* SPDX-License-Identifier: MIT */

import { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { schema as Db } from "../schema";

type PatientInsert = typeof Db.patient.$inferInsert;

/**
 * Generates a 7-character alphanumeric patient ID starting with 'P-'
 * Format: P-XXXXX where X is alphanumeric (A-Z, 0-9)
 */
function generatePatientId(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = 'P-';
  for (let i = 0; i < 5; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

/**
 * Seeds the database with test patient records.
 */
export async function seedPatients(db: PostgresJsDatabase<typeof Db>) {
  console.log("Seeding patients...");

  // Test patient data with realistic information - 40 patients
  const patients: PatientInsert[] = [
    {
      patId: generatePatientId(),
      patMrnId: "MRN001234",
      patName: "John Michael Doe",
      patFirstName: "John",
      patLastName: "Doe",
      patMiddleName: "Michael",
      birthDate: new Date("1985-03-15"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Springfield",
      stateCName: "Illinois",
      zip: "62701",
      countryCName: "United States",
      homePhone: "555-123-4567",
      workPhone: "555-987-6543",
      emailAddress: "john.doe@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Christian",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN005678",
      patName: "Jane Elizabeth Smith",
      patFirstName: "Jane",
      patLastName: "Smith",
      patMiddleName: "Elizabeth",
      birthDate: new Date("1992-07-22"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Chicago",
      stateCName: "Illinois",
      zip: "60601",
      countryCName: "United States",
      homePhone: "555-234-5678",
      emailAddress: "jane.smith@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      intrptrNeededYn: "No",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN009876",
      patName: "Carlos Antonio Rodriguez",
      patFirstName: "Carlos",
      patLastName: "Rodriguez",
      patMiddleName: "Antonio",
      birthDate: new Date("1978-11-08"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Aurora",
      stateCName: "Illinois",
      zip: "60505",
      countryCName: "United States",
      homePhone: "555-345-6789",
      workPhone: "555-876-5432",
      emailAddress: "carlos.rodriguez@email.com",
      ethnicGroupCName: "Hispanic or Latino",
      languageCName: "Spanish",
      religionCName: "Catholic",
      intrptrNeededYn: "Yes",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN011223",
      patName: "Sarah Marie Johnson",
      patFirstName: "Sarah",
      patLastName: "Johnson",
      patMiddleName: "Marie",
      birthDate: new Date("1965-04-30"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Naperville",
      stateCName: "Illinois",
      zip: "60540",
      countryCName: "United States",
      homePhone: "555-456-7890",
      emailAddress: "sarah.johnson@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Baptist",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN033445",
      patName: "Michael Wei Chen",
      patFirstName: "Michael",
      patLastName: "Chen",
      patMiddleName: "Wei",
      birthDate: new Date("1990-12-03"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Schaumburg",
      stateCName: "Illinois",
      zip: "60173",
      countryCName: "United States",
      homePhone: "555-567-8901",
      workPhone: "555-765-4321",
      emailAddress: "michael.chen@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Buddhist",
      intrptrNeededYn: "No",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN044556",
      patName: "Emily Rose Wilson",
      patFirstName: "Emily",
      patLastName: "Wilson",
      patMiddleName: "Rose",
      birthDate: new Date("1988-06-14"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Rockford",
      stateCName: "Illinois",
      zip: "61101",
      countryCName: "United States",
      homePhone: "555-678-9012",
      emailAddress: "emily.wilson@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Methodist",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN055667",
      patName: "David James Brown",
      patFirstName: "David",
      patLastName: "Brown",
      patMiddleName: "James",
      birthDate: new Date("1975-09-28"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Peoria",
      stateCName: "Illinois",
      zip: "61602",
      countryCName: "United States",
      homePhone: "555-789-0123",
      workPhone: "555-654-3210",
      emailAddress: "david.brown@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Presbyterian",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN066778",
      patName: "Maria Guadalupe Garcia",
      patFirstName: "Maria",
      patLastName: "Garcia",
      patMiddleName: "Guadalupe",
      birthDate: new Date("1982-02-17"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Joliet",
      stateCName: "Illinois",
      zip: "60431",
      countryCName: "United States",
      homePhone: "555-890-1234",
      emailAddress: "maria.garcia@email.com",
      ethnicGroupCName: "Hispanic or Latino",
      languageCName: "Spanish",
      religionCName: "Catholic",
      intrptrNeededYn: "Yes",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN077889",
      patName: "Robert Lee Taylor",
      patFirstName: "Robert",
      patLastName: "Taylor",
      patMiddleName: "Lee",
      birthDate: new Date("1970-12-05"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Elgin",
      stateCName: "Illinois",
      zip: "60120",
      countryCName: "United States",
      homePhone: "555-901-2345",
      workPhone: "555-543-2109",
      emailAddress: "robert.taylor@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Lutheran",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN088990",
      patName: "Lisa Ann Davis",
      patFirstName: "Lisa",
      patLastName: "Davis",
      patMiddleName: "Ann",
      birthDate: new Date("1995-08-11"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Waukegan",
      stateCName: "Illinois",
      zip: "60085",
      countryCName: "United States",
      homePhone: "555-012-3456",
      emailAddress: "lisa.davis@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Episcopal",
      intrptrNeededYn: "No",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN099001",
      patName: "James Patrick O'Connor",
      patFirstName: "James",
      patLastName: "O'Connor",
      patMiddleName: "Patrick",
      birthDate: new Date("1963-01-20"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Decatur",
      stateCName: "Illinois",
      zip: "62521",
      countryCName: "United States",
      homePhone: "555-123-4567",
      emailAddress: "james.oconnor@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Catholic",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN100112",
      patName: "Angela Marie Thompson",
      patFirstName: "Angela",
      patLastName: "Thompson",
      patMiddleName: "Marie",
      birthDate: new Date("1987-05-03"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Champaign",
      stateCName: "Illinois",
      zip: "61820",
      countryCName: "United States",
      homePhone: "555-234-5678",
      workPhone: "555-432-1098",
      emailAddress: "angela.thompson@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Baptist",
      intrptrNeededYn: "No",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN111223",
      patName: "Ahmed Hassan Ali",
      patFirstName: "Ahmed",
      patLastName: "Ali",
      patMiddleName: "Hassan",
      birthDate: new Date("1980-10-15"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Bloomington",
      stateCName: "Illinois",
      zip: "61701",
      countryCName: "United States",
      homePhone: "555-345-6789",
      emailAddress: "ahmed.ali@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "Arabic",
      religionCName: "Muslim",
      intrptrNeededYn: "Yes",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN122334",
      patName: "Jennifer Lynn White",
      patFirstName: "Jennifer",
      patLastName: "White",
      patMiddleName: "Lynn",
      birthDate: new Date("1991-07-08"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Normal",
      stateCName: "Illinois",
      zip: "61761",
      countryCName: "United States",
      homePhone: "555-456-7890",
      emailAddress: "jennifer.white@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Non-denominational",
      intrptrNeededYn: "No",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN133445",
      patName: "Kevin Michael Murphy",
      patFirstName: "Kevin",
      patLastName: "Murphy",
      patMiddleName: "Michael",
      birthDate: new Date("1974-03-22"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Quincy",
      stateCName: "Illinois",
      zip: "62301",
      countryCName: "United States",
      homePhone: "555-567-8901",
      workPhone: "555-321-0987",
      emailAddress: "kevin.murphy@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Catholic",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN144556",
      patName: "Priya Sharma Patel",
      patFirstName: "Priya",
      patLastName: "Patel",
      patMiddleName: "Sharma",
      birthDate: new Date("1986-11-12"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Carbondale",
      stateCName: "Illinois",
      zip: "62901",
      countryCName: "United States",
      homePhone: "555-678-9012",
      emailAddress: "priya.patel@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "Hindi",
      religionCName: "Hindu",
      intrptrNeededYn: "Yes",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN155667",
      patName: "Christopher Paul Anderson",
      patFirstName: "Christopher",
      patLastName: "Anderson",
      patMiddleName: "Paul",
      birthDate: new Date("1968-04-18"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Rock Island",
      stateCName: "Illinois",
      zip: "61201",
      countryCName: "United States",
      homePhone: "555-789-0123",
      workPhone: "555-210-9876",
      emailAddress: "christopher.anderson@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Methodist",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN166778",
      patName: "Michelle Rose Jackson",
      patFirstName: "Michelle",
      patLastName: "Jackson",
      patMiddleName: "Rose",
      birthDate: new Date("1993-09-07"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Moline",
      stateCName: "Illinois",
      zip: "61265",
      countryCName: "United States",
      homePhone: "555-890-1234",
      emailAddress: "michelle.jackson@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Baptist",
      intrptrNeededYn: "No",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN177889",
      patName: "Daniel Scott Martin",
      patFirstName: "Daniel",
      patLastName: "Martin",
      patMiddleName: "Scott",
      birthDate: new Date("1977-12-25"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Galesburg",
      stateCName: "Illinois",
      zip: "61401",
      countryCName: "United States",
      homePhone: "555-901-2345",
      emailAddress: "daniel.martin@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Lutheran",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN188990",
      patName: "Rebecca Jane Lewis",
      patFirstName: "Rebecca",
      patLastName: "Lewis",
      patMiddleName: "Jane",
      birthDate: new Date("1984-06-30"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Danville",
      stateCName: "Illinois",
      zip: "61832",
      countryCName: "United States",
      homePhone: "555-012-3456",
      workPhone: "555-109-8765",
      emailAddress: "rebecca.lewis@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Presbyterian",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN199001",
      patName: "Steven Robert Clark",
      patFirstName: "Steven",
      patLastName: "Clark",
      patMiddleName: "Robert",
      birthDate: new Date("1971-08-14"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Elgin",
      stateCName: "Illinois",
      zip: "60120",
      countryCName: "United States",
      homePhone: "555-123-4567",
      emailAddress: "steven.clark@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Episcopal",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN200112",
      patName: "Lisa Ann Rodriguez",
      patFirstName: "Lisa",
      patLastName: "Rodriguez",
      patMiddleName: "Ann",
      birthDate: new Date("1989-02-28"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Joliet",
      stateCName: "Illinois",
      zip: "60431",
      countryCName: "United States",
      homePhone: "555-234-5678",
      emailAddress: "lisa.rodriguez@email.com",
      ethnicGroupCName: "Hispanic or Latino",
      languageCName: "Spanish",
      religionCName: "Catholic",
      intrptrNeededYn: "Yes",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN211223",
      patName: "Matthew James Wilson",
      patFirstName: "Matthew",
      patLastName: "Wilson",
      patMiddleName: "James",
      birthDate: new Date("1965-11-05"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Naperville",
      stateCName: "Illinois",
      zip: "60540",
      countryCName: "United States",
      homePhone: "555-345-6789",
      workPhone: "555-543-2109",
      emailAddress: "matthew.wilson@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Methodist",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN222334",
      patName: "Amanda Grace Taylor",
      patFirstName: "Amanda",
      patLastName: "Taylor",
      patMiddleName: "Grace",
      birthDate: new Date("1992-04-17"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Schaumburg",
      stateCName: "Illinois",
      zip: "60173",
      countryCName: "United States",
      homePhone: "555-456-7890",
      emailAddress: "amanda.taylor@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Baptist",
      intrptrNeededYn: "No",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN233445",
      patName: "Brian Keith Moore",
      patFirstName: "Brian",
      patLastName: "Moore",
      patMiddleName: "Keith",
      birthDate: new Date("1978-09-23"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Evanston",
      stateCName: "Illinois",
      zip: "60201",
      countryCName: "United States",
      homePhone: "555-567-8901",
      emailAddress: "brian.moore@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Lutheran",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN244556",
      patName: "Samantha Joy Davis",
      patFirstName: "Samantha",
      patLastName: "Davis",
      patMiddleName: "Joy",
      birthDate: new Date("1985-12-11"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Des Plaines",
      stateCName: "Illinois",
      zip: "60016",
      countryCName: "United States",
      homePhone: "555-678-9012",
      workPhone: "555-210-9876",
      emailAddress: "samantha.davis@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Presbyterian",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN255667",
      patName: "Carlos Miguel Hernandez",
      patFirstName: "Carlos",
      patLastName: "Hernandez",
      patMiddleName: "Miguel",
      birthDate: new Date("1973-06-02"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Cicero",
      stateCName: "Illinois",
      zip: "60804",
      countryCName: "United States",
      homePhone: "555-789-0123",
      emailAddress: "carlos.hernandez@email.com",
      ethnicGroupCName: "Hispanic or Latino",
      languageCName: "Spanish",
      religionCName: "Catholic",
      intrptrNeededYn: "Yes",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN266778",
      patName: "Nicole Marie Garcia",
      patFirstName: "Nicole",
      patLastName: "Garcia",
      patMiddleName: "Marie",
      birthDate: new Date("1990-01-19"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Berwyn",
      stateCName: "Illinois",
      zip: "60402",
      countryCName: "United States",
      homePhone: "555-890-1234",
      emailAddress: "nicole.garcia@email.com",
      ethnicGroupCName: "Hispanic or Latino",
      languageCName: "Spanish",
      religionCName: "Catholic",
      intrptrNeededYn: "Yes",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN277889",
      patName: "Timothy Alan Johnson",
      patFirstName: "Timothy",
      patLastName: "Johnson",
      patMiddleName: "Alan",
      birthDate: new Date("1967-07-26"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Oak Park",
      stateCName: "Illinois",
      zip: "60301",
      countryCName: "United States",
      homePhone: "555-901-2345",
      workPhone: "555-321-0987",
      emailAddress: "timothy.johnson@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Non-denominational",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN288990",
      patName: "Rachel Elizabeth Brown",
      patFirstName: "Rachel",
      patLastName: "Brown",
      patMiddleName: "Elizabeth",
      birthDate: new Date("1988-03-13"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Skokie",
      stateCName: "Illinois",
      zip: "60076",
      countryCName: "United States",
      homePhone: "555-012-3456",
      emailAddress: "rachel.brown@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Jewish",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN299001",
      patName: "Gregory Thomas Miller",
      patFirstName: "Gregory",
      patLastName: "Miller",
      patMiddleName: "Thomas",
      birthDate: new Date("1976-10-08"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Palatine",
      stateCName: "Illinois",
      zip: "60067",
      countryCName: "United States",
      homePhone: "555-123-4567",
      emailAddress: "gregory.miller@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Catholic",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN300112",
      patName: "Stephanie Lynn Wilson",
      patFirstName: "Stephanie",
      patLastName: "Wilson",
      patMiddleName: "Lynn",
      birthDate: new Date("1994-05-21"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Arlington Heights",
      stateCName: "Illinois",
      zip: "60004",
      countryCName: "United States",
      homePhone: "555-234-5678",
      emailAddress: "stephanie.wilson@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Methodist",
      intrptrNeededYn: "No",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN311223",
      patName: "Anthony Joseph Martinez",
      patFirstName: "Anthony",
      patLastName: "Martinez",
      patMiddleName: "Joseph",
      birthDate: new Date("1969-08-16"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Mount Prospect",
      stateCName: "Illinois",
      zip: "60056",
      countryCName: "United States",
      homePhone: "555-345-6789",
      workPhone: "555-432-1098",
      emailAddress: "anthony.martinez@email.com",
      ethnicGroupCName: "Hispanic or Latino",
      languageCName: "Spanish",
      religionCName: "Catholic",
      intrptrNeededYn: "Yes",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN322334",
      patName: "Kimberly Sue Anderson",
      patFirstName: "Kimberly",
      patLastName: "Anderson",
      patMiddleName: "Sue",
      birthDate: new Date("1983-11-29"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Hoffman Estates",
      stateCName: "Illinois",
      zip: "60169",
      countryCName: "United States",
      homePhone: "555-456-7890",
      emailAddress: "kimberly.anderson@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Baptist",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN333445",
      patName: "Jason David Thomas",
      patFirstName: "Jason",
      patLastName: "Thomas",
      patMiddleName: "David",
      birthDate: new Date("1972-02-14"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Streamwood",
      stateCName: "Illinois",
      zip: "60107",
      countryCName: "United States",
      homePhone: "555-567-8901",
      emailAddress: "jason.thomas@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Lutheran",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN344556",
      patName: "Melissa Dawn Jackson",
      patFirstName: "Melissa",
      patLastName: "Jackson",
      patMiddleName: "Dawn",
      birthDate: new Date("1987-09-04"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Carol Stream",
      stateCName: "Illinois",
      zip: "60188",
      countryCName: "United States",
      homePhone: "555-678-9012",
      workPhone: "555-210-9876",
      emailAddress: "melissa.jackson@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Presbyterian",
      intrptrNeededYn: "No",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN355667",
      patName: "Ryan Christopher White",
      patFirstName: "Ryan",
      patLastName: "White",
      patMiddleName: "Christopher",
      birthDate: new Date("1975-12-07"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Wheeling",
      stateCName: "Illinois",
      zip: "60090",
      countryCName: "United States",
      homePhone: "555-789-0123",
      emailAddress: "ryan.white@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Episcopal",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN366778",
      patName: "Laura Michelle Harris",
      patFirstName: "Laura",
      patLastName: "Harris",
      patMiddleName: "Michelle",
      birthDate: new Date("1991-04-25"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Buffalo Grove",
      stateCName: "Illinois",
      zip: "60089",
      countryCName: "United States",
      homePhone: "555-890-1234",
      emailAddress: "laura.harris@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Methodist",
      intrptrNeededYn: "No",
      advDirectiveYn: "No"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN377889",
      patName: "Eric William Clark",
      patFirstName: "Eric",
      patLastName: "Clark",
      patMiddleName: "William",
      birthDate: new Date("1970-01-31"),
      sexCName: "Male",
      patStatusCName: "Alive",
      city: "Lincolnshire",
      stateCName: "Illinois",
      zip: "60069",
      countryCName: "United States",
      homePhone: "555-901-2345",
      workPhone: "555-321-0987",
      emailAddress: "eric.clark@email.com",
      ethnicGroupCName: "Not Hispanic or Latino",
      languageCName: "English",
      religionCName: "Non-denominational",
      intrptrNeededYn: "No",
      advDirectiveYn: "Yes"
    },
    {
      patId: generatePatientId(),
      patMrnId: "MRN388990",
      patName: "Heather Rose Rodriguez",
      patFirstName: "Heather",
      patLastName: "Rodriguez",
      patMiddleName: "Rose",
      birthDate: new Date("1986-07-12"),
      sexCName: "Female",
      patStatusCName: "Alive",
      city: "Vernon Hills",
      stateCName: "Illinois",
      zip: "60061",
      countryCName: "United States",
      homePhone: "555-012-3456",
      emailAddress: "heather.rodriguez@email.com",
      ethnicGroupCName: "Hispanic or Latino",
      languageCName: "Spanish",
      religionCName: "Catholic",
      intrptrNeededYn: "Yes",
      advDirectiveYn: "Yes"
    }
  ];

  try {
    // Use upsert to handle existing data
    const insertedPatients = [];
    for (const patientData of patients) {
      const result = await db.insert(Db.patient)
        .values(patientData)
        .onConflictDoUpdate({
          target: Db.patient.patId,
          set: patientData
        })
        .returning();
      insertedPatients.push(result[0]);
    }
    console.log(`Successfully seeded ${insertedPatients.length} patients`);
    return insertedPatients;
  } catch (error) {
    console.error("Error seeding patients:", error);
    throw error;
  }
}