CREATE TABLE "patient" (
	"pat_id" text PRIMARY KEY NOT NULL,
	"pat_name" text NOT NULL,
	"birth_date" timestamp with time zone,
	"death_date" timestamp with time zone,
	"ssn" text,
	"pat_mrn_id" text,
	"city" text,
	"state_c_name" text,
	"county_c_name" text,
	"country_c_name" text,
	"zip" text,
	"tmp_city" text,
	"tmp_state_c_name" text,
	"tmp_county_c_name" text,
	"tmp_country_c_name" text,
	"tmp_zip" text,
	"tmp_home_phone" text,
	"tmp_addr_start_dt" timestamp with time zone,
	"home_phone" text,
	"work_phone" text,
	"email_address" text,
	"ethnic_group_c_name" text,
	"religion_c_name" text,
	"language_c_name" text,
	"reg_date" timestamp with time zone,
	"reg_status_c_name" text,
	"legal_status_c_name" text,
	"birth_status_c_name" text,
	"medicare_num" text,
	"medicaid_num" text,
	"adv_directive_yn" text,
	"adv_directive_date" timestamp with time zone,
	"organ_donor_yn" text,
	"cur_pcp_prov_id_prov_name" text,
	"cur_prim_loc_id_loc_name" text,
	"ped_mult_birth_ord" integer,
	"ped_mult_birth_tot" integer,
	"create_user_id" text,
	"create_user_id_name" text,
	"rec_create_pat_id" text,
	"rec_create_pat_id_name" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
